// Regenerates sw.js with a precache list built from the actual file tree, so
// the offline manifest can't drift from what ships. `npm run build:sw`.

import { readdirSync, statSync, writeFileSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const SKIP = new Set(['.git', 'node_modules', 'tools', 'docs', '.github']);
const KEEP = /\.(html|css|js|png|webmanifest|svg|woff2?)$/;

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    if (SKIP.has(name) || name.startsWith('.')) continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (KEEP.test(name) && name !== 'sw.js') out.push('./' + relative(root, full));
  }
  return out;
}

const assets = ['./', ...walk(root).sort()];

// Cache version is content-derived: any shipped byte changing busts the cache.
let hash = 0;
for (const f of assets.filter((a) => a !== './')) {
  const b = readFileSync(join(root, f));
  for (let i = 0; i < b.length; i++) hash = (Math.imul(hash, 31) + b[i]) | 0;
}
const version = 'thela-' + (hash >>> 0).toString(36);

const sw = `// GENERATED by tools/build-sw.mjs — do not edit by hand.
// Cache-first over a fully precached shell: the whole game is static, so once
// it is installed it plays with the aeroplane mode on.

const CACHE = '${version}';
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Navigations fall back to the cached shell so a deep link works offline.
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req).catch(() => caches.match('./index.html').then((r) => r || caches.match('./'))),
    );
    return;
  }

  e.respondWith(
    caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
      }
      return res;
    })),
  );
});
`;

writeFileSync(join(root, 'sw.js'), sw);
console.log(`sw.js → ${version} · ${assets.length} assets precached`);
